### ISSUE TITLE
Weird margin in context menus

### ISSUE THREAD

**Issue by marcmsk** [valinet/Win11DisableRoundedCorners#11]
Hi  Valentin-Gabriel,

firstly I want to thank you for this plugin. 

Personally I don't have problem with rounded windows, I've just decided to use it order get rid of the weird, annoying padding in old-style context menus. It's default behavior when you change back context menu so it is Window's bug, and this is be more feature request rather than reporting a bug. Find please the screenshot bellow:

![screenshot](https://user-images.githubusercontent.com/15047876/141298549-46e08ea9-0f06-4cca-b39a-d27197afea81.png)

I have set back rounded corners, but with plugin installed it is the same obviously. I am wondering how complex it would be to fix that problem within your plugin. 

Thank you in advance for considering it.

**Comment by valinet** [comment]
I recommend following what is described here: https://github.com/valinet/ExplorerPatcher/issues/18 to bring back the regular gray highlight that looked proper from initial Windows 11 builds.

Thanks
