### ISSUE TITLE
PC doesn't boot up

### ISSUE THREAD

**Issue by Roza2188** [valinet/Win11DisableRoundedCorners#12]
I run exe and then decided to remove rounded icons run exe again and PC has frozen. Now when I boot up it's just infinite loading?

**Comment by valinet** [comment]
Use System Restore, or boot in preinstallation environment and replace the file from backup.

**Comment by Roza2188** [comment]
> Use System Restore, or boot in preinstallation environment and replace the file from backup.

Safe boot works, what can I do If I don't have a system restore point?

**Comment by valinet** [comment]
Try:
* `sfc /scannow`
* `DISM.exe /Online /Cleanup-image /Restorehealth`
* replace faulty `uDWM.dll` with original `uDWM.dll` from your build

**Comment by drelnar0** [comment]
ye its virus same happened to me

**Comment by valinet** [comment]
> ye its virus same happened to me

🤣

Program with 100 lines of code, all posted online, executable is easy to disassemble, “it’s a virus”. Yeah, nothing more to say…

**Comment by giovanni-orciuolo** [comment]
Dude it's literally written in the README "make sure to backup the original DLL in case something goes wrong, use software at your own risk" and now you say it's virus rofl

**Comment by ReezesMC** [comment]
> Try:
> 
> * `sfc /scannow`
> * `DISM.exe /Online /Cleanup-image /Restorehealth`
> * replace faulty `uDWM.dll` with original `uDWM.dll` from your build

I dont have the original `uDWM.dll` what do I do

**Comment by valinet** [comment]
What’s not clear in sfc /scannow and then reboot?
