### ISSUE TITLE
Restore the old Windows 10 window frame style for Windows 11

### ISSUE THREAD

**Issue by nayomisa** [valinet/Win11DisableRoundedCorners#14]
[Moonique from the Virtual Customs forum has managed to restore the window frames and title bar so that the theming in those areas is possible, but had to replace several Windows 11 files with Windows 10 files.](https://virtualcustoms.net/showthread.php/87578-Post-Your-Windows-11-Desktop/page10?p=355740&viewfull=1#post355740)

Is it possible to do that or integrate that feature into this patch?

**Comment by valinet** [comment]
I don't have a single clue about what you are talking about. And to be honest, I really neither have the time to understand it, nor the curiosity to understand it. As long as someone is willing to work on something, it generally can be implemented.

**Comment by nayomisa** [comment]
I was referring to the borders, in Windows 10 they were themeable, but in Windows 11 they were displaced by the Mica material, now the themes only theme the part of the window buttons, and no longer the whole "frame":
Example:
![image](https://user-images.githubusercontent.com/96040248/146626061-f6947008-ead2-46a1-80f7-d75665245b33.png)

But look at this [image](https://virtualcustoms.net/attachment.php?attachmentid=91096&d=1639220189), it was accomplished by Moonique by mixing files from Windows 10 21H2 and Windows 11 21H2, but it took away the functionality to update the system.
Since this project patches files related to the desktop composition, maybe you can restore the edges, instead of just the corners.

Sorry if it's too much to ask or if I didn't explain well at the beginning, maybe this goes in [valinet/ExplorerPatcher](https://github.com/valinet/ExplorerPatcher), because this is a previous feature of the system, [StartAllBack](https://www.startallback.com/) and [namazso/SecureUxTheme](https://github.com/namazso/SecureUxTheme) work just fine but they don't do this edge/corners stuff 😞

**Comment by valinet** [comment]
Yeah, I still don't really understand. The theme engine does not draw borders anymore? Yeah, maybe they just hardcode it now to no border. Anyway, sorry, but I am not taking on this, it presents no academic or utilitarian interest to me and I have tons of other stuff to be taking on. But good luck with your research!
