### ISSUE TITLE
sfc /scannow wont let me patch again

### ISSUE THREAD

**Issue by ThaBluNate** [valinet/Win11DisableRoundedCorners#18]
I ran sfc /scannow, but now i cant go back to box corners, all i ask for is a way to force it to install or uninstall, regardless of the state of dwm, like a command line argument:

_Win11DisableOrRestoreRoundedCorners.exe --restore
Win11DisableOrRestoreRoundedCorners.exe --patch_

Every time i run the patcher it tells me it cant restore dwm
(it's already original, and it doesn't have the perms to do so)

**Comment by valinet** [comment]
I suggest you try [ExplorerPatcher](https://github.com/valinet/ExplorerPatcher), it already has a better version of this patch built-in and much more. Alternatively, if you just want a patch standalone, the component that patches DWM from EP is kept in a separate repository, you can follow the instructions [here](https://github.com/valinet/ep_dwm) to get that executable alone which does a much better job than this.

**Comment by ValZapod** [comment]
This is because of a new update I think. It is now extra slow, but still works.
