### ISSUE TITLE
Unable to find pattern in file

### ISSUE THREAD

**Issue by IsraelNS902** [valinet/Win11DisableRoundedCorners#2]
When I run the executable as administrator from the file explorer I get the following error. 

```
Function address is: 0x227a4
Unable to find pattern in file.
```

For the sake of it, I copied the "uDWM.dll" file that was outputted alongside the executable in my Downloads folder & pasted\overwrote it in the "C:\Windows\System32" directory using the copy command in the WinRE command prompt after locating my Windows drive letter, and no changes were made to the corners upon continuing to Windows 11 afterwards.

**Video:** https://streamable.com/bl8hix
**Screenshot:** https://i.imgur.com/pCIqLNQ.png
Windows 11 Dev Build 22468.1000

**Comment by IsraelNS902** [comment]
Here's an image of what CTopLevelWindows::GetEffectCornerStyle looks like in IDA if that's of any help.

![image](https://user-images.githubusercontent.com/91391668/135805618-d8c50d57-e238-4797-8f70-4d8cd4259aaf.png)

**Comment by valinet** [comment]
Yeah, I know why it says that. Okay, I simplified the patching, now it should work, can you please try again? Version 1.0.0.2.
Thanks.

**Comment by IsraelNS902** [comment]
@valinet 

I ran the executable, then restated the system, but I get stuck on the boot animation. 

Thank you btw for your speediness, true GOAT.

![20211004_075347](https://user-images.githubusercontent.com/91391668/135839422-14d76d6e-6ba9-4429-b813-e4de921e27fa.jpg)

**Comment by IsraelNS902** [comment]
Was able to perform a system restore, I'm going to try it again.

**Comment by IsraelNS902** [comment]
> Yeah, I know what it says that. Okay, I simplified the patching, now it should work, can you please try again? Version 1.0.0.2. Thanks.

The update works perfect! 

![image](https://user-images.githubusercontent.com/91391668/135843267-019c0cd8-728b-4919-91fb-ec7cbfb2a23d.png)


Thank you @valinet you're a God! 🙏🙏
