### ISSUE TITLE
After the updates, the corners are rounded again

### ISSUE THREAD

**Issue by Onmp314** [valinet/Win11DisableRoundedCorners#24]
Hello,

I have an annoying problem. In build 22000.556, the previously activated tool named "Win11DisableRoundedCorners" stops working. Enabling this tool will result in the error that the old DWM cannot be restored. Can it be fixed without damaging the DWM (which restores Windows Basic, which causes the system to stop working properly)?

Greetings,
Onmp314

**Comment by valinet** [comment]
Use ExplorerPatcher, much better implementation.

**Comment by Onmp314** [comment]
OK, thanks ;)
