### ISSUE TITLE
Rounded corners not removed on alt-tab windows

### ISSUE THREAD

**Issue by m0d1nst4ll3r** [valinet/Win11DisableRoundedCorners#25]
Flawless if it weren't for the fact that the windows that appear when alt-tabbing still have rounded corners.

Ex: https://i.imgur.com/kymfvF0.png

**Comment by eightballocto** [comment]
I haven't tried it just yet, but does it also disable the rounded corners on push notifications?

**Comment by m0d1nst4ll3r** [comment]
Hmmm you mean windows notifications bottom right? I haven't paid attention and I've disabled most of them since I hate robots trying to grab my attention, but the calendar is still rounded, and when I disable windows defender, the notification is also still rounded, so it would seem the answer to your question is no :(

**Comment by valinet** [comment]
> A simple utility that cold patches dwm (uDWM.dll) in order to disable window rounded corners in Windows 11

window rounded corners

Not toasts, not some random previews in a random utility etc. This utility cannot predict whether an app draws a rectangle that would represent a window with rounded corners and decide against that. No. It simply patches dwm and the code path that affects how it draws window decorations for windows that need decorations from it. Simple as that. Anything else that’s not this - yeah, not supported by this.
