### ISSUE TITLE
Ik this is not related to Windows11DisableRoundedCorners, but some questions i wanna ask

### ISSUE THREAD

**Issue by Pixel556** [valinet/Win11DisableRoundedCorners#27]
1. Does Translucent TB work with ExplorerPatcher?
2. Can you add an option to enable the search bar for the Windows 10 taskbar in ExplorerPatcher?

**Comment by valinet** [comment]
1. Idk. Why can't you try it yourself? Afaik, TranslucentTB is free and broadly available. I don't use that app.
2. Not working on it. Instead, I recommend [Everything Toolbar](https://github.com/stnkl/EverythingToolbar).

**Comment by Pixel556** [comment]
Thanks. I think I'll stay with the acrylic effect taskbar.
