### ISSUE TITLE
How to Enable again ?

### ISSUE THREAD

**Issue by chuongmep** [valinet/Win11DisableRoundedCorners#3]
Dear Valinet 
How we can Enable Again Rounded Corners ? 
Thanks you.

**Comment by valinet** [comment]
Run the app again.

**Comment by chuongmep** [comment]
It dump windows and i can't startup after that.

**Comment by valinet** [comment]
The disclaimer says it is experimental. The patch is pretty simple to do manually if you want. Idk, in my limited testing on my computer and laptop, it works. Use system restore or cmd in PE to restore a working `uDWM.dll` and you should be good to go again. I cannot test in every scenario and configuration, it is a tool that comes with this kind of inconveniences, if it happens. Make sure to also leave it running until the command window disappears, only then is it finished running.
