### ISSUE TITLE
pc bricked

### ISSUE THREAD

**Issue by SuperMarioYAHOOYAHOO** [valinet/Win11DisableRoundedCorners#45]
Pc showing a black screen with my curser after trying to disable. help

**Comment by McfearJnr** [comment]
Try windows + shift + ctrl + b

**Comment by McfearJnr** [comment]
(That restarts/reinstalls you graphic drivers)

**Comment by SuperMarioYAHOOYAHOO** [comment]
i already ran a fresh install. im on windows 10 now.
