### ISSUE TITLE
Rounded corners remain on taskbar icon menu

### ISSUE THREAD

**Issue by IsraelNS902** [valinet/Win11DisableRoundedCorners#5]
When you right click an icon on the taskbar rounded corners remain enabled.

![Untitled](https://user-images.githubusercontent.com/91391668/136504987-26df13ba-80c7-4cb5-b0ab-6d75eca65203.png)

**Comment by valinet** [comment]
That’s not an issue with this program, those are custom drawn to have rounded icons, this program JUST patches the compositor to draw default window corners squared. If you draw rounded stuff in your code, how could this program know and patch that? And, like, should it do it, I strongly don’t think so…
