### ISSUE TITLE
Successfully changed DACL. Unable to prepare for replacing system file.

### ISSUE THREAD

**Issue by ggg1221** [valinet/Win11DisableRoundedCorners#50]
**Successfully changed DACL.
Unable to prepare for replacing system file.**

This error showed up what do i do also there is two of the backups?!
![resim](https://github.com/valinet/Win11DisableRoundedCorners/assets/67912895/2b9a856c-607f-4c1d-b15f-48895669cc78)

Edit: If I run the exe again it kills dwm process but There is still Rounded corners I tried deleting the backups the 
`uDWM_win11drc.bak` this file can be deleted, and i deleted it still same
`uDWM_win11drc.bak1` I cannot delete this one tho

edit : I ran sfc /scannow
and chkdsk
But still the same

**Comment by fishhon** [comment]
you need to give yourself permission in security in properties.
