### ISSUE TITLE
Broke DWM 

### ISSUE THREAD

**Issue by PinchToDebug** [valinet/Win11DisableRoundedCorners#6]
it didn’t restore properly and it broke my whole installation.

**Comment by valinet** [comment]
Just run `sfc /scannow`, it will restore the original DLL. It comes with no warranties. I say it works, I tested it just fine on 22000.194 a million times. It works especially if one lets it finish its job (i.e. the console window should go away), if you have Internet when running it etc. Also, the tool is provided AS IS, of course patching the compositor that is used to draw everything on the screen comes with some inconveniences if it goes wrong. But it does not break the system, one only has to restore the original `uDWM.dll` from a backup which the README clearly states the user should do.

**Comment by PinchToDebug** [comment]
I fixed it with booting to the advanced startup and I was able to find the original dll hidden in syswow64 ig, then I copied it to an other drive, booted back up, and copied from there to system32 literally blindfolded (didn’t let me copy it from th3 advanced startup ) it was a lot of fun. it was totally my mistake to not make a back up. all in all great work :)

**Comment by valinet** [comment]
I am glad that you fixed it. Yeah, always make a backup. Programs may sometimes have bugs or fail under certain conditions. A manual backup never makes any harm.
